# Generated by Django 3.0.4 on 2020-04-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_pubDate', models.DateTimeField(verbose_name='question date published')),
                ('question_title', models.TextField()),
                ('question_detail', models.TextField()),
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('Answer_author', models.CharField(max_length=30)),
                ('Answer_content', models.TextField()),
                ('Answer_pubDate', models.DateTimeField(verbose_name='answer date published')),
                ('Answer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Question')),
            ],
        ),
    ]
